# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parse/v1/pdf_parser.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'parse/v1/pdf_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.message.common.v1 import s3_pb2 as common_dot_v1_dot_s3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19parse/v1/pdf_parser.proto\x12\x08parse.v1\x1a\x12\x63ommon/v1/s3.proto\"*\n\x08PDFCover\x12\x10\n\x08page_num\x18\x01 \x01(\r\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x01\"\xdf\x02\n\nPDFSegment\x12\x14\n\x0c\x63hapter_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12.\n\x04type\x18\x03 \x01(\x0e\x32 .parse.v1.PDFSegment.SegmentType\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12 \n\x05image\x18\x05 \x01(\x0b\x32\x11.common.v1.S3File\x12\"\n\x06\x63overs\x18\x06 \x03(\x0b\x32\x12.parse.v1.PDFCover\x12\x1b\n\x13related_segment_ids\x18\x07 \x03(\t\x12\x14\n\x0creference_id\x18\x08 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\t \x01(\t\"d\n\x0bSegmentType\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n\tTYPE_TEXT\x10\x01\x12\x0e\n\nTYPE_IMAGE\x10\x02\x12\x10\n\x0cTYPE_FORMULA\x10\x03\x12\x0e\n\nTYPE_TABLE\x10\x04\"\x1c\n\x0bPDFMetadata\x12\r\n\x05title\x18\x01 \x01(\t\"1\n\x0ePDFParserInput\x12\x1f\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x11.common.v1.S3File\"\x83\x01\n\x0fPDFParserOutput\x12\x1f\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x11.common.v1.S3File\x12\'\n\x08metadata\x18\x02 \x01(\x0b\x32\x15.parse.v1.PDFMetadata\x12&\n\x08segments\x18\x03 \x03(\x0b\x32\x14.parse.v1.PDFSegmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parse.v1.pdf_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFCOVER']._serialized_start=59
  _globals['_PDFCOVER']._serialized_end=101
  _globals['_PDFSEGMENT']._serialized_start=104
  _globals['_PDFSEGMENT']._serialized_end=455
  _globals['_PDFSEGMENT_SEGMENTTYPE']._serialized_start=355
  _globals['_PDFSEGMENT_SEGMENTTYPE']._serialized_end=455
  _globals['_PDFMETADATA']._serialized_start=457
  _globals['_PDFMETADATA']._serialized_end=485
  _globals['_PDFPARSERINPUT']._serialized_start=487
  _globals['_PDFPARSERINPUT']._serialized_end=536
  _globals['_PDFPARSEROUTPUT']._serialized_start=539
  _globals['_PDFPARSEROUTPUT']._serialized_end=670
# @@protoc_insertion_point(module_scope)
